version: "3.6"

services:
  reverse-proxy:
    image: pmbot/reverse-proxy:${REVERSE_PROXY_VERSION:-latest}
    restart: ${RESTART_POLICY?RESTART_POLICY}
    ports:
      - ${PUBLIC_IP?PUBLIC_IP}:${PORT?PORT}:80

  backend:
    image: ${REPOSITORY}pmbot/backend${PREMIUM_SUFFIX}:${BACKEND_VERSION:-latest}
    restart: ${RESTART_POLICY?RESTART_POLICY}
    environment:
      APP_UI_URL: ${APP_UI_URL?APP_UI_URL}
    volumes:
      - ${SECRETS_VOLUME?SECRETS_VOLUME}:/secrets

  frontend:
    image: ${REPOSITORY}pmbot/ui${PREMIUM_SUFFIX}:${FRONTEND_VERSION:-latest}
    environment:
      PMBOT_API_URL: ${API_URL?API_URL}
    restart: ${RESTART_POLICY?RESTART_POLICY}

  mongo:
    image: mongo:4.2-bionic
    restart: ${RESTART_POLICY?RESTART_POLICY}
    volumes:
      - ${MONGO_VOLUME?MONGO_VOLUME}:/data/db

volumes:
  mongo:
  secrets:
