version: "3.6"

services:
  reverse-proxy:
    image: pmbot/reverse-proxy
    restart: unless-stopped
    ports:
      - 9118:80

  frontend:
    image: pmbot/ui
    restart: unless-stopped

  backend:
    image: pmbot/backend-community
    restart: unless-stopped
    volumes:
      - secrets:/secrets

  mongo:
    image: mongo:4.2-bionic
    restart: unless-stopped
    volumes:
      - mongo:/data/db

volumes:
  mongo:
  secrets:
